apiVersion: v1
kind: Service
metadata:
  name: nginx-env-service
spec:
  type: NodePort
  selector:
    app: nginx-env-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
