version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27016:27017"   # Host:Container
    volumes:
      - mongo_data:/data/db   # Mount named volume inside /data/db

volumes:
  mongo_data:    # Named volume declared
